
package proyecto1_ed2;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author romina
 */
public class Formulario extends javax.swing.JFrame {
    DefaultListModel nombres=new DefaultListModel();
    DefaultListModel nombresS=new DefaultListModel();
    
    /**
     * Creates new form Formulario
     */
    Vector vec=new Vector();
    Vector vSospechoso=new Vector();
    Matriz A=new Matriz(12,8/2);
    
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);//para centrar el formulario
        nombres=new DefaultListModel();
        lstNombres.setModel(nombres);
        nombresS=new DefaultListModel();
        lstSospechosos.setModel(nombresS);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNombres = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblMatriz = new javax.swing.JTable();
        jtf_dimencionar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_EliminarT = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        tfAlumnosSospechosos = new javax.swing.JTextField();
        btnAgregarSospechosos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSospechosos = new javax.swing.JList<>();
        btn_iniciar1 = new javax.swing.JPanel();
        lb_iniciar = new javax.swing.JLabel();
        PanelCabesera = new javax.swing.JPanel();
        btn_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        PanelFondo.setBackground(new java.awt.Color(204, 204, 204));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese la Lista de estudiantes");
        PanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese los 2 alumnos sospechos");
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jScrollPane1.setViewportView(lstNombres);

        PanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 140));

        jtblMatriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtblMatriz.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblMatriz.setAutoscrolls(false);
        jtblMatriz.setRowHeight(40);
        jtblMatriz.setShowHorizontalLines(true);
        jScrollPane4.setViewportView(jtblMatriz);

        PanelFondo.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 370, 540));
        PanelFondo.add(jtf_dimencionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 40, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Representacion Grafica");
        PanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        btn_Agregar.setText("Agregar");
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseExited(evt);
            }
        });
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        PanelFondo.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, -1));

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        PanelFondo.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        btn_EliminarT.setText("Eliminar Todo");
        btn_EliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarTActionPerformed(evt);
            }
        });
        PanelFondo.add(btn_EliminarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelFondo.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 230, -1));
        PanelFondo.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, -1));

        label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label1.setText("Nombre");
        PanelFondo.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        PanelFondo.add(tfAlumnosSospechosos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 130, 30));

        btnAgregarSospechosos.setText("Agregar");
        btnAgregarSospechosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSospechososActionPerformed(evt);
            }
        });
        PanelFondo.add(btnAgregarSospechosos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jScrollPane2.setViewportView(lstSospechosos);

        PanelFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 40));

        lb_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_iniciar.setText("Iniciar");
        lb_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_iniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_iniciarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_iniciar1Layout = new javax.swing.GroupLayout(btn_iniciar1);
        btn_iniciar1.setLayout(btn_iniciar1Layout);
        btn_iniciar1Layout.setHorizontalGroup(
            btn_iniciar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_iniciar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_iniciar1Layout.setVerticalGroup(
            btn_iniciar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_iniciar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelFondo.add(btn_iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, 30));

        PanelCabesera.setBackground(new java.awt.Color(255, 0, 0));
        PanelCabesera.setForeground(new java.awt.Color(204, 204, 204));
        PanelCabesera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setLayout(new java.awt.BorderLayout());

        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");
        lb_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMouseExited(evt);
            }
        });
        btn_exit.add(lb_exit, java.awt.BorderLayout.CENTER);

        PanelCabesera.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 60, 30));

        PanelFondo.add(PanelCabesera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("PROYECO 1");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
       /* String  hard=tf_nombre.getText();
        nombres.addElement(hard);
        tf_nombre.setText("");
        */
        String nombre=tf_nombre.getText();
        vec.AgregarNombre(nombre);
        nombres.addElement(nombre);
        
        
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        int eli=lstNombres.getSelectedIndex();
        vec.eliminarNommbre(eli);
        nombres.remove(eli);
        int n=vec.getN();
        JOptionPane.showMessageDialog(null,"cantidad de nombres "+n);
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_EliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarTActionPerformed
        // TODO add your handling code here:
        int elitodo=lstNombres.getSelectedIndex();
        nombres.removeAllElements();
        
    }//GEN-LAST:event_btn_EliminarTActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarSospechososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSospechososActionPerformed
        // TODO add your handling code here:
        String  nsospechoso=tfAlumnosSospechosos.getText();
        nombresS.addElement(nsospechoso);
      tfAlumnosSospechosos.setText("");
        vSospechoso.AgregarNombre(nsospechoso);
        
    }//GEN-LAST:event_btnAgregarSospechososActionPerformed

    private void btn_AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseEntered
        btn_Agregar.setBackground(Color.red);
    }//GEN-LAST:event_btn_AgregarMouseEntered

    private void btn_AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseExited
         btn_Agregar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_AgregarMouseExited

    private void lb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseClicked
         System.exit(0);
    }//GEN-LAST:event_lb_exitMouseClicked

    private void lb_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseEntered
        btn_exit.setBackground(Color.red);
    }//GEN-LAST:event_lb_exitMouseEntered

    private void lb_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseExited
         btn_exit.setBackground(Color.WHITE);
    }//GEN-LAST:event_lb_exitMouseExited

    private void lb_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_iniciarMouseClicked
         //A.setFilas(5);
       // A.setColumnas(5);
       A.iniciarTablero(0);
       vec.cargadoNombres();
       A.cargarNombre(vec,0,0);//alt+30 =▲ alt+31=▼ alt+2=☻
       ///A.verificando(vec, 0, 0);
       A.verificando(vec);
       
       
        //jtblMatriz.setRowCount(A.getFilas());
      
        /////////////////
        DefaultTableModel model = (DefaultTableModel) jtblMatriz.getModel();
        model.setRowCount(A.getFilas());//cantidad de filas 
        model.setColumnCount(A.getColumnas());//cantidad de columnas
        
       // Matriz m=new Matriz(4,4);
        
        for (int i = 0; i < A.getFilas(); i++) {
            for (int j = 0; j < A.getColumnas(); j++) {
                jtblMatriz.setValueAt(A.getElemento(i,j), i, j);
                
            }
            
        }
    }//GEN-LAST:event_lb_iniciarMouseClicked

    private void lb_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_iniciarMouseEntered
         btn_iniciar1.setBackground(Color.RED);
         lb_iniciar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lb_iniciarMouseEntered

    private void lb_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_iniciarMouseExited
         btn_iniciar1.setBackground(Color.WHITE);
         lb_iniciar.setForeground(Color.BLACK);
         
    }//GEN-LAST:event_lb_iniciarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }
    
    
    //Mostrar matrix
    public void MostrarMatirz(int matriz[][],int n){
        DefaultTableModel model = (DefaultTableModel) jtblMatriz.getModel();
        model.setRowCount(4);//cantidad de filas 
        model.setColumnCount(4);//cantidad de columnas
        Matriz m=new Matriz(4,4);
        m.cargarMatriz(vec);
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                jtblMatriz.setValueAt(m.getElemento(i,j), i, j);
                
            }
            
        }
        //b.seRepite(1);//desde la posicion 1 enpieza a contar
    } 
    //
    public int[][] matrizEspiral(int n){
        int[][] matriz = new int[10][10];
        int nlimite= n-1;
        int inicio=0;
        int c=1;
        while(c<=(n*n)){
            for (int i = inicio; i <= nlimite; i++) {//ciclo 1
                matriz[inicio][i]=c++;           
            }
            for (int i = inicio+1; i <= nlimite; i++) {//ciclo 2
                matriz[i][nlimite]=c++;           
            }
            for (int i = nlimite-1; i >= inicio; i--) {//ciclo 3
                matriz[nlimite][i]=c++;           
            }
            for (int i = nlimite-1; i >= inicio+1; i--) {//ciclo 3
                matriz[i][inicio]=c++;           
            }
            nlimite=nlimite-1;
            inicio=inicio+1;
        }
        return matriz;
      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCabesera;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAgregarSospechosos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_EliminarT;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_iniciar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtblMatriz;
    private javax.swing.JTextField jtf_dimencionar;
    private java.awt.Label label1;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_iniciar;
    private javax.swing.JList<String> lstNombres;
    private javax.swing.JList<String> lstSospechosos;
    private javax.swing.JTextField tfAlumnosSospechosos;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables

    void setVisiblie(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
